// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBq1PA8D4ggqG_RmumqfrwHZs2iluk_2l4',
    appId: '1:457484292778:android:5549f5068cb97232c0f6d3',
    messagingSenderId: '457484292778',
    projectId: 'handong-eats-61f3d',
    storageBucket: 'handong-eats-61f3d.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2-1BuDl1amDme42sjZoSNGd_I9pesWw8',
    appId: '1:457484292778:web:fc79f706d3af330dc0f6d3',
    messagingSenderId: '457484292778',
    projectId: 'handong-eats-61f3d',
    authDomain: 'handong-eats-61f3d.firebaseapp.com',
    storageBucket: 'handong-eats-61f3d.firebasestorage.app',
    measurementId: 'G-EKWMD8N1HL',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmJbih66Gzu-Eufl0YGrctbXkAE4XAwYQ',
    appId: '1:457484292778:ios:370976992d30cbb9c0f6d3',
    messagingSenderId: '457484292778',
    projectId: 'handong-eats-61f3d',
    storageBucket: 'handong-eats-61f3d.firebasestorage.app',
    iosBundleId: 'com.example.handongEats',
  );
}